plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.appleitorcbr'
version = '0.1.0'

dependencies {
  implementation 'io.github.realburst:unrar5j:2.0.3'
}

android {
  namespace "expo.modules.appleitorcbr"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
